quarkus:
  datasource:
    jdbc:
      url: jdbc:mysql://localhost:3306/products
      driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  hibernate-orm:
    dialect: org.hibernate.dialect.MySQL8Dialect
    database:
      generation: drop-and-create
